name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build . --file Dockerfile -t app

    - name: Run Docker container
      run: docker run -d -p 8080:8080 --name app_container -t app

    # Check if Flask app is up and running
    - name: Wait for Flask to be ready
      run: |
        until curl -s http://localhost:8080 > /dev/null; do
          echo "Waiting for Flask to start..."
          sleep 5
        done
        echo "Flask is up and running!"

    - name: Run client script
      run: docker exec app_container python app/client.py
