name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build . --file Dockerfile -t app

    - name: Run Docker container
      run: docker run -d -p 8080:8080 --name app_container app

    - name: Wait for Flask to be ready
      run: |
        echo "Waiting for Flask to start..."
        for i in {1..15}; do
          if curl -s http://localhost:8080/ > /dev/null; then
            echo "Flask is up!"
            exit 0
          fi
          echo "Still waiting..."
          sleep 2
        done
        echo "Flask did not start in time!"
        docker logs app_container
        exit 1

    - name: Run client script
      run: docker exec app_container python app/client.py
